### ISSUE TITLE
Add support for Typescript (docco 0.7.0)

### ISSUE THREAD

**Issue by cblair** [DavidSouther/grunt-docco#41]
I think all that needs to be done is update the package.json to point to the new version.

**Comment by neocotic** [comment]
I'll try to have a look at this tonight. I think we'll best bump our own version to 0.4.0 since 0.7.0 contains a breaking change, so we should also reflect that since we basically act as a proxy for grunt. Otherwise, we could break websites and/or links to them if we're used to build the docs.

If anyone's interested, it seems that the breaking change is that the generated HTML files no longer contain the extension of the original file (e.g. `test.html` instead of `test.js.html`).

**Comment by neocotic** [comment]
I've bumped to version of our docco dependency to `~0.7.0` so this should not be fixed, therefore I'm closing this issue. Please feel free to reopen if you have any issues with the new version, `0.4.0`.

**Comment by cblair** [comment]
Awesome, thanks neocotic, I'll test the update.

**Comment by cblair** [comment]
Works perfect! Thanks again.
